name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      contents: write  # 关键：授予写入权限

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # ======== 静态站点专用配置（无需构建） ========
      - name: Prepare public directory
        run: |
          mkdir -p public
          # 复制所有可见文件（排除.git等隐藏文件）
          find . -maxdepth 1 ! -name '.' ! -name '..' ! -name '.git' ! -name '.github' -exec cp -r {} public/ \;
          
      # ======== Jekyll 站点示例 ========
      # - name: Set up Ruby
      #   uses: ruby/setup-ruby@v1
      #   with:
      #     ruby-version: '3.1'
      # - name: Install dependencies
      #   run: bundle install
      # - name: Build site
      #   run: bundle exec jekyll build --destination ./public

      # ======== 通用部署步骤 ========
      - name: Verify public directory
        run: ls -la public/  # 调试：确认目录内容

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          force_orphan: true  # 强制清空目标分支历史
